import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import '/flutter_flow/custom_functions.dart';
import '/flutter_flow/lat_lng.dart';
import '/flutter_flow/place.dart';
import '/flutter_flow/uploaded_file.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/backend/supabase/supabase.dart';
import '/auth/firebase_auth/auth_util.dart';

String? countryFlag(String? countryName) {
  if (countryName == null) {
    return null;
  }

  final countryInfoJson = {
    "Afghanistan": {"dialcode": "+93", "code": "AF"},
    "Albania": {"dialcode": "+355", "code": "AL"},
    "Algeria": {"dialcode": "+213", "code": "DZ"},
    "Andorra": {"dialcode": "+376", "code": "AD"},
    "Angola": {"dialcode": "+244", "code": "AO"},
    "Antigua and Barbuda": {"dialcode": "+1-268", "code": "AG"},
    "Argentina": {"dialcode": "+54", "code": "AR"},
    "Armenia": {"dialcode": "+374", "code": "AM"},
    "Australia": {"dialcode": "+61", "code": "AU"},
    "Austria": {"dialcode": "+43", "code": "AT"},
    "Azerbaijan": {"dialcode": "+994", "code": "AZ"},
    "Bahamas": {"dialcode": "+1-242", "code": "BS"},
    "Bahrain": {"dialcode": "+973", "code": "BH"},
    "Bangladesh": {"dialcode": "+880", "code": "BD"},
    "Barbados": {"dialcode": "+1-246", "code": "BB"},
    "Belarus": {"dialcode": "+375", "code": "BY"},
    "Belgium": {"dialcode": "+32", "code": "BE"},
    "Belize": {"dialcode": "+501", "code": "BZ"},
    "Benin": {"dialcode": "+229", "code": "BJ"},
    "Bhutan": {"dialcode": "+975", "code": "BT"},
    "Bolivia": {"dialcode": "+591", "code": "BO"},
    "Bosnia and Herzegovina": {"dialcode": "+387", "code": "BA"},
    "Botswana": {"dialcode": "+267", "code": "BW"},
    "Brazil": {"dialcode": "+55", "code": "BR"},
    "Brunei": {"dialcode": "+673", "code": "BN"},
    "Bulgaria": {"dialcode": "+359", "code": "BG"},
    "Burkina Faso": {"dialcode": "+226", "code": "BF"},
    "Burundi": {"dialcode": "+257", "code": "BI"},
    "Cabo Verde": {"dialcode": "+238", "code": "CV"},
    "Cambodia": {"dialcode": "+855", "code": "KH"},
    "Cameroon": {"dialcode": "+237", "code": "CM"},
    "Canada": {"dialcode": "+1", "code": "CA"},
    "Central African Republic": {"dialcode": "+236", "code": "CF"},
    "Chad": {"dialcode": "+235", "code": "TD"},
    "Chile": {"dialcode": "+56", "code": "CL"},
    "China": {"dialcode": "+86", "code": "CN"},
    "Colombia": {"dialcode": "+57", "code": "CO"},
    "Comoros": {"dialcode": "+269", "code": "KM"},
    "Congo, Democratic Republic of the": {"dialcode": "+243", "code": "CD"},
    "Congo, Republic of the": {"dialcode": "+242", "code": "CG"},
    "Costa Rica": {"dialcode": "+506", "code": "CR"},
    "Croatia": {"dialcode": "+385", "code": "HR"},
    "Cuba": {"dialcode": "+53", "code": "CU"},
    "Cyprus": {"dialcode": "+357", "code": "CY"},
    "Czech Republic": {"dialcode": "+420", "code": "CZ"},
    "Denmark": {"dialcode": "+45", "code": "DK"},
    "Djibouti": {"dialcode": "+253", "code": "DJ"},
    "Dominica": {"dialcode": "+1-767", "code": "DM"},
    "Dominican Republic": {"dialcode": "+1-809", "code": "DO"},
    "Ecuador": {"dialcode": "+593", "code": "EC"},
    "Egypt": {"dialcode": "+20", "code": "EG"},
    "El Salvador": {"dialcode": "+503", "code": "SV"},
    "Equatorial Guinea": {"dialcode": "+240", "code": "GQ"},
    "Eritrea": {"dialcode": "+291", "code": "ER"},
    "Estonia": {"dialcode": "+372", "code": "EE"},
    "Eswatini": {"dialcode": "+268", "code": "SZ"},
    "Ethiopia": {"dialcode": "+251", "code": "ET"},
    "Fiji": {"dialcode": "+679", "code": "FJ"},
    "Finland": {"dialcode": "+358", "code": "FI"},
    "France": {"dialcode": "+33", "code": "FR"},
    "Gabon": {"dialcode": "+241", "code": "GA"},
    "Gambia": {"dialcode": "+220", "code": "GM"},
    "Georgia": {"dialcode": "+995", "code": "GE"},
    "Germany": {"dialcode": "+49", "code": "DE"},
    "Ghana": {"dialcode": "+233", "code": "GH"},
    "Greece": {"dialcode": "+30", "code": "GR"},
    "Grenada": {"dialcode": "+1-473", "code": "GD"},
    "Guatemala": {"dialcode": "+502", "code": "GT"},
    "Guinea": {"dialcode": "+224", "code": "GN"},
    "Guinea-Bissau": {"dialcode": "+245", "code": "GW"},
    "Guyana": {"dialcode": "+592", "code": "GY"},
    "Haiti": {"dialcode": "+509", "code": "HT"},
    "Honduras": {"dialcode": "+504", "code": "HN"},
    "Hungary": {"dialcode": "+36", "code": "HU"},
    "Iceland": {"dialcode": "+354", "code": "IS"},
    "India": {"dialcode": "+91", "code": "IN"},
    "Indonesia": {"dialcode": "+62", "code": "ID"},
    "Iran": {"dialcode": "+98", "code": "IR"},
    "Iraq": {"dialcode": "+964", "code": "IQ"},
    "Ireland": {"dialcode": "+353", "code": "IE"},
    "Italy": {"dialcode": "+39", "code": "IT"},
    "Jamaica": {"dialcode": "+1-876", "code": "JM"},
    "Japan": {"dialcode": "+81", "code": "JP"},
    "Jordan": {"dialcode": "+962", "code": "JO"},
    "Kazakhstan": {"dialcode": "+7", "code": "KZ"},
    "Kenya": {"dialcode": "+254", "code": "KE"},
    "Kiribati": {"dialcode": "+686", "code": "KI"},
    "Korea, North": {"dialcode": "+850", "code": "KP"},
    "Korea, South": {"dialcode": "+82", "code": "KR"},
    "Kosovo": {"dialcode": "+383", "code": "XK"},
    "Kuwait": {"dialcode": "+965", "code": "KW"},
    "Kyrgyzstan": {"dialcode": "+996", "code": "KG"},
    "Laos": {"dialcode": "+856", "code": "LA"},
    "Latvia": {"dialcode": "+371", "code": "LV"},
    "Lebanon": {"dialcode": "+961", "code": "LB"},
    "Lesotho": {"dialcode": "+266", "code": "LS"},
    "Liberia": {"dialcode": "+231", "code": "LR"},
    "Libya": {"dialcode": "+218", "code": "LY"},
    "Liechtenstein": {"dialcode": "+423", "code": "LI"},
    "Lithuania": {"dialcode": "+370", "code": "LT"},
    "Luxembourg": {"dialcode": "+352", "code": "LU"},
    "Madagascar": {"dialcode": "+261", "code": "MG"},
    "Malawi": {"dialcode": "+265", "code": "MW"},
    "Malaysia": {"dialcode": "+60", "code": "MY"},
    "Maldives": {"dialcode": "+960", "code": "MV"},
    "Mali": {"dialcode": "+223", "code": "ML"},
    "Malta": {"dialcode": "+356", "code": "MT"},
    "Marshall Islands": {"dialcode": "+692", "code": "MH"},
    "Mauritania": {"dialcode": "+222", "code": "MR"},
    "Mauritius": {"dialcode": "+230", "code": "MU"},
    "Mexico": {"dialcode": "+52", "code": "MX"},
    "Micronesia": {"dialcode": "+691", "code": "FM"},
    "Moldova": {"dialcode": "+373", "code": "MD"},
    "Monaco": {"dialcode": "+377", "code": "MC"},
    "Mongolia": {"dialcode": "+976", "code": "MN"},
    "Montenegro": {"dialcode": "+382", "code": "ME"},
    "Morocco": {"dialcode": "+212", "code": "MA"},
    "Mozambique": {"dialcode": "+258", "code": "MZ"},
    "Myanmar": {"dialcode": "+95", "code": "MM"},
    "Namibia": {"dialcode": "+264", "code": "NA"},
    "Nauru": {"dialcode": "+674", "code": "NR"},
    "Nepal": {"dialcode": "+977", "code": "NP"},
    "Netherlands": {"dialcode": "+31", "code": "NL"},
    "New Zealand": {"dialcode": "+64", "code": "NZ"},
    "Nicaragua": {"dialcode": "+505", "code": "NI"},
    "Niger": {"dialcode": "+227", "code": "NE"},
    "Nigeria": {"dialcode": "+234", "code": "NG"},
    "North Macedonia": {"dialcode": "+389", "code": "MK"},
    "Norway": {"dialcode": "+47", "code": "NO"},
    "Oman": {"dialcode": "+968", "code": "OM"},
    "Pakistan": {"dialcode": "+92", "code": "PK"},
    "Palau": {"dialcode": "+680", "code": "PW"},
    "Panama": {"dialcode": "+507", "code": "PA"},
    "Papua New Guinea": {"dialcode": "+675", "code": "PG"},
    "Paraguay": {"dialcode": "+595", "code": "PY"},
    "Peru": {"dialcode": "+51", "code": "PE"},
    "Philippines": {"dialcode": "+63", "code": "PH"},
    "Poland": {"dialcode": "+48", "code": "PL"},
    "Portugal": {"dialcode": "+351", "code": "PT"},
    "Qatar": {"dialcode": "+974", "code": "QA"},
    "Romania": {"dialcode": "+40", "code": "RO"},
    "Russia": {"dialcode": "+7", "code": "RU"},
    "Rwanda": {"dialcode": "+250", "code": "RW"},
    "Saint Kitts and Nevis": {"dialcode": "+1-869", "code": "KN"},
    "Saint Lucia": {"dialcode": "+1-758", "code": "LC"},
    "Saint Vincent and the Grenadines": {"dialcode": "+1-784", "code": "VC"},
    "Samoa": {"dialcode": "+685", "code": "WS"},
    "San Marino": {"dialcode": "+378", "code": "SM"},
    "Sao Tome and Principe": {"dialcode": "+239", "code": "ST"},
    "Saudi Arabia": {"dialcode": "+966", "code": "SA"},
    "Senegal": {"dialcode": "+221", "code": "SN"},
    "Serbia": {"dialcode": "+381", "code": "RS"},
    "Seychelles": {"dialcode": "+248", "code": "SC"},
    "Sierra Leone": {"dialcode": "+232", "code": "SL"},
    "Singapore": {"dialcode": "+65", "code": "SG"},
    "Slovakia": {"dialcode": "+421", "code": "SK"},
    "Slovenia": {"dialcode": "+386", "code": "SI"},
    "Solomon Islands": {"dialcode": "+677", "code": "SB"},
    "Somalia": {"dialcode": "+252", "code": "SO"},
    "South Africa": {"dialcode": "+27", "code": "ZA"},
    "South Sudan": {"dialcode": "+211", "code": "SS"},
    "Spain": {"dialcode": "+34", "code": "ES"},
    "Sri Lanka": {"dialcode": "+94", "code": "LK"},
    "Sudan": {"dialcode": "+249", "code": "SD"},
    "Suriname": {"dialcode": "+597", "code": "SR"},
    "Sweden": {"dialcode": "+46", "code": "SE"},
    "Switzerland": {"dialcode": "+41", "code": "CH"},
    "Syria": {"dialcode": "+963", "code": "SY"},
    "Taiwan": {"dialcode": "+886", "code": "TW"},
    "Tajikistan": {"dialcode": "+992", "code": "TJ"},
    "Tanzania": {"dialcode": "+255", "code": "TZ"},
    "Thailand": {"dialcode": "+66", "code": "TH"},
    "Timor-Leste": {"dialcode": "+670", "code": "TL"},
    "Togo": {"dialcode": "+228", "code": "TG"},
    "Tonga": {"dialcode": "+676", "code": "TO"},
    "Trinidad and Tobago": {"dialcode": "+1-868", "code": "TT"},
    "Tunisia": {"dialcode": "+216", "code": "TN"},
    "Turkey": {"dialcode": "+90", "code": "TR"},
    "Turkmenistan": {"dialcode": "+993", "code": "TM"},
    "Tuvalu": {"dialcode": "+688", "code": "TV"},
    "Uganda": {"dialcode": "+256", "code": "UG"},
    "Ukraine": {"dialcode": "+380", "code": "UA"},
    "United Arab Emirates": {"dialcode": "+971", "code": "AE"},
    "United Kingdom": {"dialcode": "+44", "code": "GB"},
    "United States of America": {"dialcode": "+1", "code": "US"},
    "Uruguay": {"dialcode": "+598", "code": "UY"},
    "Uzbekistan": {"dialcode": "+998", "code": "UZ"},
    "Vanuatu": {"dialcode": "+678", "code": "VU"},
    "Vatican City": {"dialcode": "+379", "code": "VA"},
    "Venezuela": {"dialcode": "+58", "code": "VE"},
    "Vietnam": {"dialcode": "+84", "code": "VN"},
    "Yemen": {"dialcode": "+967", "code": "YE"},
    "Zambia": {"dialcode": "+260", "code": "ZM"},
    "Zimbabwe": {"dialcode": "+263", "code": "ZW"}
  };

  final courtryCode = countryInfoJson[countryName]?["code"];
  if (courtryCode != null) {
    final countryCodeInLowerCase = courtryCode.toLowerCase();
    return 'https://flagcdn.com/h80/$countryCodeInLowerCase.png';
  }

  return null;
}
